#!/usr/bin/env python
import os
import subprocess
import sys

print('1234', flush=True)

for i in range(4):
    env = os.environ.copy()
    env['SLURM_ARRAY_TASK_ID'] = str(i + 1)
    subprocess.run(sys.argv[-1:], env=env, check=True)
