#!/usr/bin/env python
import json

payload = {
    "jobs": [
        {
            "comment": ""
        },
        {
        },
        {
            "comment": "MyTask__99914b932b"
        }
    ]
}

print(json.dumps(payload))
